name = "googleblogger26"
main = "src/index.ts"
compatibility_date = "2024-04-03"

[[d1_databases]]
binding = "DB"
database_name = "youtube-blogger-db"
database_id = "ca4b13d6-1f3e-4f27-9cfe-0ed3d64011d7"

[triggers]
crons = ["0 0 * * *", "0 6 * * *"]
